### PR TITLE
Fixes for issue #120.

### PR DESCRIPTION
**Pull request by christiantinauer**
- Extended check if field is public by also taking into account IsFamilyOrAssembly-property of FieldDefinition (now behaves like the method check).
- InheritMap now also generates groups for virtual methods of props (set, get) and events (add, remove).
- The group info is used to find out if any virtual method in the group belongs to a public type and therefore should be skipped. e.g. public interface implemented by internal class or vice a versa.

### CODE REVIEW

**Comment by christiantinauer** [comment]
@lextm Do you have an idea if/when this PR is going to be accepted?

**Comment by lextm** [comment]
I already built up some new test cases, but not yet finish reviewing this PR. It might take some more time.

**Comment by christiantinauer** [comment]
@lextm Any progress on the PR. Can I help you with the tests?

**Comment by legistek** [comment]
I just began trying out Obfuscar and ran into this issue immediately. Hope it is fixed soon as it's currently a show stopper.

**Comment by christiantinauer** [comment]
Any progress on this PR?

**Comment by lextm** [comment]
I cannot accept this PR, as it only fixed the simplest case.

Consider the following test case,
```
namespace TestClasses
{
    public interface A
    {
        int Property { get; }
        void Method();
    }

    internal interface B
    {
        int Property { get; }
    }

    internal class C : A, B
    {
        // This property should not be obfuscated.
        int A.Property
        {
            get { return 0; }
        }

        // This property should be obfuscated.
        int B.Property
        {
            get { return 1; }
        }

        // This method is not be obfuscated because it's a part of the public interface.
        public void Method()
        { }
    }
}
```

**Pull request closed without merging**
