### PR TITLE
Fix/crlf

### PR DESCRIPTION
**Pull request by casz**
Tried to do a simple two line change inside `TestHelper.cs` on [`fix/testProject`](https://github.com/obfuscar/obfuscar/compare/master...3shapeAS:fix/testProject?expand=1) but due to line ending mismatch, it appears as if I changed the whole file. 
These files are committed with CRLF where git defaults to LF.

I see also there is a mix of tabs and spaces. Perhaps a good time to introduce [`dotnet format`](https://github.com/dotnet/format)

See
https://github.com/obfuscar/obfuscar/compare/master...3shapeAS:fix/testProject?expand=1

### CODE REVIEW

**Comment by casz** [comment]
@lextm 👋

**Comment by lextm** [comment]
I have no plan to accept this right now, while there are other pull requests in review. Close it.

**Comment by casz** [comment]
... this is something git handle just fine when someone merges with upstream..

**Comment by casz** [comment]
You can very quickly verify this locally by creating a branch and modify one of the files and then merge this branch in.

**Pull request closed without merging**
