### PR TITLE
Added ability to use filter for modules

### PR DESCRIPTION
**Pull request by frblondin**
We are obfuscating a number of assemblies. When developers are adding a new project we need to declare these new projects in the configuration file.

This PR adds as a way to define multiple files at once without having to duplicate lines in the configuration. Also, as most company assemblies are following a convention Acme.XXX.dll, declaring how they should be obfuscated in one line is much more efficient.

```
<Module file="$(InPath)\SomeFile.dll">
    <Include path="obfuscar.skip.xml" />
</Module>
<Modules>
   <IncludeFiles>$(InPath)\Acme.*.dll</IncludeFiles>
   <ExcludeFiles>$(InPath)\Acme*Tests.dll</ExcludeFiles>
   <Include path="obfuscar.skip.xml" />
</Modules>
```

### CODE REVIEW

**Comment by lextm** [comment]
You should consider using a script (PowerShell for example) to generate the XML config file for Obfuscar on the fly, then there is no need to make it this complicated.

**Comment by frblondin** [comment]
It's your final call to decide to merge it or not.

Just to answer your point (scripting xml generation): when we obfuscate a software it's a very common pattern to obfuscate all made assemblies that are easily identifiable in general (MyCompany.XXX, MySoft.YYY...). Given that this is frequent, providing such capacity in Obfuscar seems to be a good idea and having to add a script to produce the xml adds unnecessary complexity if obfuscar supports file patterns.

Also, modified code doesn't seem to be complicated/over-engineered.

**Comment by lextm** [comment]
I think the complexity introduced in this pull request is the +/- filter design. It is not as obvious as MSBuild's include/exclude wildcard, https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2019

**Comment by frblondin** [comment]
I was inspired by [OpenCover filtering](https://github.com/opencover/opencover/wiki/Usage).

If you prefer ths MSbuild include/exclude format I can change it. Do you want me to change it?

**Comment by lextm** [comment]
Can this work?
```
<Module include="$(InPath)\Acme.*.dll" exclude="$(InPath)\Acme*Tests.dll" />
```

**Comment by frblondin** [comment]
In my case I want to include all assemblies (`Acme*.dll`) except a few ones (`AcmeAbc.dll`, `AcmeDef.dll`...). What I suggest is that we support a separator so that we can include/exclude multiple file patterns. Forward slash (`/`) seems to be the only character which is [not supported for file names](https://stackoverflow.com/a/31976060). That's a problem since on linux the forward slash is the path separator as you know... this is why I ended up using balanced brackets.

I propose one of the following syntax:
* Option 1
```xml
<Module include="[$(InPath)\Acme.*.dll]"
        exclude="[$(InPath)\Acme*Tests.dll],[$(InPath)\AcmeAbc.dll]">
    ...
</Module>
```
* Option 2
```xml
<Module>
    <Include>$(InPath)\Acme.*.dll</Include>
    <Exclude>$(InPath)\Acme*Tests.dll</Exclude>
    <Exclude>$(InPath)\AcmeAbc.dll</Exclude>
    ...
</Module>
```

I tend to prefer option 2 as it's closer to [MsBuild format](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2019), it's less error prone, and more readable.

**Comment by frblondin** [comment]
So, option 2? :-)

**Comment by lextm** [comment]
I wonder for option 2 if we should also change <Module> to <Modules> for clarity.

**Comment by frblondin** [comment]
I changed the implementation following your suggestion. Also, I slightly changed the name of the `Include` and `Exclude` elements because `Include` was conflicting with existing element names. I chose `IncludeFiles` and `ExcludeFiles`.

```
<Module file="$(InPath)\SomeFile.dll">
    <Include path="obfuscar.skip.xml" />
</Module>
<Modules>
   <IncludeFiles>$(InPath)\Acme.*.dll</IncludeFiles>
   <ExcludeFiles>$(InPath)\Acme*Tests.dll</ExcludeFiles>
   <Include path="obfuscar.skip.xml" />
</Modules>
```

**Comment by lextm** [comment]
Thanks. I will merge it once I updated the documentation site accordingly.

**Comment by frblondin** [comment]
Do not hesitate if you want me to create a PR for this [file](https://github.com/obfuscar/docs/blob/master/getting-started/configuration.rst).

**Comment by frblondin** [comment]
I thought we were really close to get this PR merged. That would be a nice Christmas gift 😋 .

**Comment by lextm** [comment]
It's a tough year, so let's see if it can be merged before Dec 31.

**Comment by frblondin** [comment]
Gentle reminder - please let me know how I could help.

**Comment by frblondin** [comment]
Any chance this PR gets merged in 2022?

**Comment by lextm** [comment]
Thanks for the reminder. Cherry picked on master, so close this pull request here.

**Comment by frblondin** [comment]
Thanks!

**Pull request closed without merging**
